spring.application.name=crud-java




spring.datasource.url = jdbc:postgresql://localhost:5432/escuela
spring.datasource.username = santos
spring.datasource.password = santos
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-message=always


server.port = 8081